resources:
  - namespace.yaml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v3.2.1
  - default-project.yaml

patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - argocd-cmd-params-cm.yaml
  - network-policy.yaml

namespace: argocd
