on:
  workflow_dispatch: {}
  schedule:
    - cron: '3 4 * * *'
  push:
    paths:
    - '**/*.yaml'

jobs:
  scan-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Scan Images
      uses: docker://kasuboski/trivy-scan-dir:latest
      env:
        EXCLUDED: 'voucher/vouch-proxy rancher/k3s-upgrade'
